#cloud-config
users:
  - name: mhutter
    groups: ['sshlogin']
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh-authorized-keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIfm1yYW1eWfyHGTHVgtgP2P2yY5otmHnSWUWEyNk23f rokkit2020
