---
apiVersion: v1
kind: Namespace
metadata:
  name: fip-controller

---
apiVersion: v1
kind: Secret
metadata:
  name: hcloud
  namespace: kube-system
stringData:
  token: "{{ hcloud_token }}"
  network: "{{ hcloud_network_name }}"

---
apiVersion: v1
kind: Secret
metadata:
  name: hcloud-csi
  namespace: kube-system
stringData:
  token: "{{ hcloud_token }}"

---
apiVersion: v1
kind: Secret
metadata:
  name: fip-controller-secrets
  namespace: fip-controller
stringData:
  HCLOUD_API_TOKEN: "{{ hcloud_token }}"
